### ISSUE TITLE
Enable homebrew verbose and debug mode

### ISSUE THREAD

**Issue by meichengg** [icy/pacapt#208] opened 2021-09-29 05:59 UTC
Hi, i would like to make suggestion to enable homebrew verbose and debug mode such as `-v` and `-d`. Would be nice if this is implemented not only for Homebrew but for others as well.

**Comment by icy** [comment] 2021-09-29 07:05
Hi @meichengg , I think the `-v` option is already supported (partially tho). Can you please give it a try (with `homebrew`)

```
$ pacapt -sSv
```

Relevant code below. The option (if found) will be part of `_EOPT` [3] and in theory it should be processed by the backend [4]

[1] https://github.com/icy/pacapt/blob/b733313875975c5195e543356dc4729dd77a3d01/lib/zz_main.sh#L232
[2] https://github.com/icy/pacapt/blob/b733313875975c5195e543356dc4729dd77a3d01/lib/00_core.sh#L182
[3] https://github.com/icy/pacapt/blob/b733313875975c5195e543356dc4729dd77a3d01/lib/00_core.sh#L238
[4] https://github.com/icy/pacapt/blob/b733313875975c5195e543356dc4729dd77a3d01/lib/zz_main.sh#L310

**Closed as completed** 2021-09-29 07:13 UTC

**Comment by icy** [comment] 2021-09-29 08:02
Though the issue is closed, I think there is still an option for improvement: It's because verbose and debug may not be the same thing in some (or many) situations. Please don't hesitate to reopen the ticket if you have found any issue with `-v` option. 

Thanks  a lot and enjoy `pacapt`.
